apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterip-deployment
  labels:
    app: clusterip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clusterip
  template:
    metadata:
      labels:
        app: clusterip
    spec:
      containers:
      - name: clusterip-app
        image: algheglobal/networking_k8s:1.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: clusterip-svc
  labels:
    app: clusterip
spec:
  selector:
    app: clusterip
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
